language: php
sudo: false
cache:
    yarn: true
    directories:
        - $HOME/.sonar/cache
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        - ./bin/.phpunit
    
env:
    global:
        - PHPUNIT_FLAGS="-v"
        #- SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
        - SYMFONY_DEPRECATIONS_HELPER=29
matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
        - php: 7.3
        - php: 7.1
    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev-master"

addons:
  sonarcloud:
    organization: "adachsoft-github"
    token:
      secure: ${SONAR_TOKEN}

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    #- if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
    - mv .env_travis .env
install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    #- if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - ls -lah
    - composer install ${COMPOSER_FLAGS} --no-interaction --no-scripts
    #- ./bin/phpunit install
    - ls ./bin -lah
    
    
script:
    #- composer validate --no-check-lock
    # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
    # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
    #- ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
    #php bin/phpunit
    #- sonar-scanner
    - echo "START"
    - echo "${SONAR_TOKEN}"
    - sonar-scanner 
        -Dsonar.projectKey=adachsoft_www-core 
        -Dsonar.organization=adachsoft-github 
        -Dsonar.sources=. 
        -Dsonar.host.url=https://sonarcloud.io 
        -Dsonar.login=${SONAR_TOKEN}

after_script:
    - ls -lah  

after_failure:
    - ls -lah
    